### ISSUE TITLE
check English tutorial

### ISSUE THREAD

**Issue by cdepillabout** [khibino/haskell-relational-record#10]
I've translated the [tutorial](https://github.com/khibino/haskell-relational-record/wiki/%E3%83%81%E3%83%A5%E3%83%BC%E3%83%88%E3%83%AA%E3%82%A2%E3%83%AB) in the wiki [into English](https://github.com/khibino/haskell-relational-record/wiki/Tutorial).  Please check it out and let me know if anything has been translated incorrectly!

**Comment by igrep** [comment]
Thank you very much :+1: 
I fixed a mistake (maybe you forgot to delete the words).
I didn't find any other problems.

@khibino I think it's okay to close.

**Comment by khibino** [comment]
@cdepillabout  @igrep  Thanks for your contributions!

**Comment by cdepillabout** [comment]
@igrep Thanks!
