### ISSUE TITLE
Are English documentation patches wanted?

### ISSUE THREAD

**Issue by ocharles** [khibino/haskell-relational-record#12]
Hello, thank you for this excellent library! I have noticed that the English documentation is good, but there is room for improvement. Would you like patches that use more idiomatic English?

I ask in case you are planning to much major changes.

**Comment by kazu-yamamoto** [comment]
Yes, yes, yes! We Japanese need such contributions very much. It would be highly appreciated!

No major changes are planed.

**Comment by ocharles** [comment]
Thank you - I'll see what I can find the time to do :)
