### ISSUE TITLE
Haskell Symposium paper

### ISSUE THREAD

**Issue by kazu-yamamoto** [khibino/haskell-relational-record#17]
We are writing a paper about HRR to Haskell Symposium and looking for reviewers.
The length is 6 pages since it is a experience report.
The deadline is 22nd May. Of course, early feedback would be great.

@ocharles @chrisdone @karamaan @tomjaguarpaw @meteficha
If you kindly accept our favor, please reply to this issue.
I will add you to our private repo on github.
Recommending other people are also welcome.

**Comment by tomjaguarpaw** [comment]
Sure!

**Comment by kazu-yamamoto** [comment]
@tomjaguarpaw  Thanks. I added you to our private repo. We would like to describe Opaleye in related work as you can see in comments in paper.tex. But we gave up because due to space limitation. If you guys kindly provide some text to compare HRR and Opaleye, we try to find space.
