### ISSUE TITLE
INSERT from Assignings monad?

### ISSUE THREAD

**Issue by debug-ito** [khibino/haskell-relational-record#20]
I'm pretty new to HRR, so please correct me if I'm wrong.

As far as I understand, we can construct UPDATE statements with `Assingings` monad but we CANNOT construct INSERT statements with it. I wonder why.

If that's possible, the INSERT example of http://khibino.github.io/haskell-relational-record/examples.html could be rewritten to something like:

```haskell
newBranch :: Monad m => Assignings Branch.Branch m ()
newBranch = do
  Branch.name'    <-# value "Headquarters"
  Branch.address' <-# value (Just "3882 Main St.")
  Branch.city'    <-# value (Just "Waltham")
  Branch.state'   <-# value (Just "MA")
  Branch.zip'     <-# value (Just "02451")

type InnerMonad = ...  -- I'm not sure what it should be

assigningsToInsert :: Table r -> Assignings r InnerMonad () -> Insert r
assigningsToInsert = ...

insertBranch_monad = assigningsToInsert tableOfBranch newBranch
```

I think that would be nice because

- we don't have to have `Branch1` and `piBranch1`.
- we can reuse `newBranch` for UPDATE.

The only shortcoming of this approach I can think of now is weaker type-safety, but defining and using the partial type (`Branch1`) is just as type-unsafe as the above, isn't it?

**Comment by khibino** [comment]
Thanks for your reporting.

I finally added the support of Register monad for INSERT statement in
https://github.com/khibino/haskell-relational-record/commit/be1e318fc848173a950596b329c8aa6140a2b2fb ,
https://github.com/khibino/haskell-relational-record/commit/7d35bd3119b768d705197ddfba084bf5a2f102da and
https://github.com/khibino/haskell-relational-record/commit/002bbcbdc058f188d32fee25ec096369dba7e604 .

And, I updated the example of constant INSERT using Register monad.
( https://github.com/khibino/haskell-relational-record/commit/bd2455f171e098431843d00a397a48f45fc3ddc1 )

I have recognized this, but I have hesitated to enlarge supported API set :)

**Comment by debug-ito** [comment]
Thank you for your great work!

**Comment by khibino** [comment]
I uploaded new release (relational-query-0.8.0.1) involving these new definitions.
