### ISSUE TITLE
"nulls last" with postgresql

### ISSUE THREAD

**Issue by carlosdagos** [khibino/haskell-relational-record#43]
Hello, I'm learning HRR and it's awesome.

I'm trying to do an `ORDER BY field DESC NULLS LAST` with Postgresql [1], and can't find any examples implementing this.

How can I go about it?

Thanks.

[1] http://www.postgresql.org/docs/8.3/static/queries-order.html

**Comment by khibino** [comment]
Hi.
I added NULLS FIRST and NULL LAST feature in https://github.com/khibino/haskell-relational-record/commit/3c2bb2a9324d1d1b6e90b3b5ccb41b9d47893eea ,
and I released new versions including this feature 
http://hackage.haskell.org/package/relational-query-0.8.7.1
http://hackage.haskell.org/package/relational-query-0.9.4.1
