### ISSUE TITLE
JoinRestriction not documented in global documentation

### ISSUE THREAD

**Issue by ryantm** [khibino/haskell-relational-record#47]
In https://hackage.haskell.org/package/relational-record-0.1.5.1/docs/Database-Relational-Query-Documentation.html

when I click on the JoinRestriction links it does not go to a part of the documentation that describes how to construct a JoinRestriction type. It would be nice if it was documented in a way that would make it clear how to use the documented join functions.

**Comment by khibino** [comment]
Updated documentation is uploaded.

http://hackage.haskell.org/package/relational-record-0.1.6.0/docs/Database-Relational-Query-Documentation.html#t:JoinRestriction
