### ISSUE TITLE
documentation for hrr in the haskelldocumentation repository

### ISSUE THREAD

**Issue by cdepillabout** [khibino/haskell-relational-record#7]
It looks like FPcomplete and Michael Snoyman recently started the [Commercial Haskell](https://github.com/commercialhaskell/commercialhaskell#readme) group.  They are putting together a repository of [documentation](https://github.com/commercialhaskell/haskelldocumentation) for teaching [intermediate-level](https://github.com/commercialhaskell/commercialhaskell/blob/master/proposal/intermediate-haskell-documentation.md) haskell.  Here is the [email thread](https://groups.google.com/forum/#!topic/commercialhaskell/Ou00AvRdDTU) introducing the documentation repository.

Looking through the [outline](https://github.com/commercialhaskell/haskelldocumentation/blob/master/outline/intermediate-haskell.md), it looks like they have a section for [databases](https://github.com/commercialhaskell/haskelldocumentation/blob/master/outline/intermediate-haskell.md#database-programming).

I think it would be great if there were an article about HRR.  Especially since it would be the first database article.  

The last email in the email thread linked above says "Like I say in the README, commit access to this repo should be given out freely, so if someone wants to get involved, just go for it, no permission needed."  So it sounds like an article on HRR would probably be accepted.

After the article was completed, it could probably be submitted to reddit as well.

I would be willing to do translations from Japanese to English.  Or even just check over an article written in English.

**Comment by kazu-yamamoto** [comment]
Now I'm discussing this with Michael in private.

**Comment by cdepillabout** [comment]
Okay, sounds good!  I'll be interested to hear about it!

**Comment by chrisdone** [comment]
What is haskell-relational-record's relation to haskelldb?

**Comment by kazu-yamamoto** [comment]
HRR is a next generation of HaskellDB. The main author of HRR, Hibino, used to use HaskellDB. Through this experience, he found some shortcomings of HaskellDB:

- No support for outer join
- No support for group by
- No support for place holder
- Non-standard records are used
- Conflict of column names
- Need to prepare many boilerplate

Correct me if I'm wrong.

HRR was designed to solve all problems above.

**Comment by kazu-yamamoto** [comment]
@cdepillabout Since we have no human power to write another tutorial about HRR, I just added a link to HRR homepage.

https://github.com/commercialhaskell/haskelldocumentation/pull/8

**Comment by cdepillabout** [comment]
@kazu-yamamoto Okay sounds good!

**Comment by chrisdone** [comment]
@kazu-yamamoto Thanks, that clarifies.
