### ISSUE TITLE
(Patch) make identifier sanitization more stringent

### ISSUE THREAD

**Issue by ibispi** [khibino/haskell-relational-record#74]
I am writing this for my friend, since he doesn't have a github account,

"Please merge this patch that makes identifier sanitization more stringent.
I tried to contact you via email, with no luck.
http://paste.debian.net/plain/1084302

**Comment by khibino** [comment]
This patch is merged and released in names-th-0.3.0.1
http://hackage.haskell.org/package/names-th-0.3.0.1

Thanks for contribution.
